version: '3.7'
services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    deploy:
      mode: replicated
      replicas: 1
  
  app: 
    build: .
    image: gozem-app
    depends_on:
      - redis
    environment: 
      APP_GOOGLE_MAPS_API_KEY: 'AIzaSyBrRh0NjtrSopoOrG-4_W3OP0nmzSDQK-M'
      APP_SERVER_PORT: 3000
      APP_REDIS_PORT: 6379
    ports:
      - "3000:3000"
    deploy:
      mode: replicated
      replicas: 1