apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  type: {{ .Values.app.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.containers.port }}
  selector:
    app: {{ .Values.app.name }}
